import { createFileRoute, Link } from "@tanstack/react-router";
import type { ComponentType, ReactNode } from "react";
import { Bell, Bot, Boxes, ChevronRight, Database, KeyRound, Monitor, Save, ShieldCheck, SlidersHorizontal, Workflow } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { useNexo, type PlatformSettings } from "@/lib/store";

export const Route = createFileRoute("/settings")({ component: SettingsPage });

type ToggleKey = "compactNavigation" | "reduceMotion" | "notifyHandoffs" | "notifyFailures" | "notifyDeployments" | "confirmHighRiskTools" | "allowLocalFallback";

function SettingsPage() {
  const settings = useNexo((s) => s.settings);
  const updateSettings = useNexo((s) => s.updateSettings);
  const workspace = useNexo((s) => s.workspaces.find((item) => item.id === s.workspaceId));
  const toggle = (key: ToggleKey) => updateSettings({ [key]: !settings[key] } as Partial<PlatformSettings>);

  return <AppShell title="Configurações"><div className="max-w-5xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge tone="live">Control plane</Badge><h1 className="mt-3 font-display text-3xl font-semibold tracking-tight">Configurações</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted">Defina como o Nexo Cloud deve funcionar para sua equipe, seus agentes e seus ambientes. Preferências sensíveis continuam protegidas no servidor.</p></div><Button variant="secondary" onClick={() => updateSettings({})}><Save className="size-4" />Preferências salvas automaticamente</Button></div>

    <div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_18rem]"><div className="space-y-6">
      <SettingsSection icon={Monitor} title="Experiência do console" description="Ajuste a forma como você navega e acompanha a operação."><ToggleRow label="Navegação compacta" description="Use menos espaço vertical na barra lateral." checked={settings.compactNavigation} onChange={() => toggle("compactNavigation")} /><ToggleRow label="Reduzir movimento" description="Desative transições não essenciais da interface." checked={settings.reduceMotion} onChange={() => toggle("reduceMotion")} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Tema"><select value={settings.appearance} onChange={(e) => updateSettings({ appearance: e.target.value as PlatformSettings["appearance"] })} className="h-10 w-full rounded-md border border-border bg-bg px-3 text-sm"><option value="dark">Escuro</option><option value="light">Claro</option><option value="system">Sistema</option></select></Field><Field label="Atualização operacional"><select value={settings.autoRefreshSeconds} onChange={(e) => updateSettings({ autoRefreshSeconds: Number(e.target.value) as PlatformSettings["autoRefreshSeconds"] })} className="h-10 w-full rounded-md border border-border bg-bg px-3 text-sm"><option value="5">A cada 5 segundos</option><option value="15">A cada 15 segundos</option><option value="30">A cada 30 segundos</option><option value="60">A cada 60 segundos</option></select></Field></div></SettingsSection>

      <SettingsSection icon={Bot} title="Padrões para agentes" description="Valores iniciais usados ao criar novos agentes. Cada agente pode ser customizado depois."><div className="grid gap-4 sm:grid-cols-2"><Field label="Janela de memória"><Input type="number" min={2} max={100} value={settings.defaultMemoryWindow} onChange={(e) => updateSettings({ defaultMemoryWindow: Math.min(100, Math.max(2, Number(e.target.value) || 2)) })} /><span className="mt-1 block text-xs text-muted">Quantidade de mensagens consideradas no contexto.</span></Field><Field label="Temperatura padrão"><Input type="number" min={0} max={1} step={0.05} value={settings.defaultTemperature} onChange={(e) => updateSettings({ defaultTemperature: Math.min(1, Math.max(0, Number(e.target.value) || 0)) })} /><span className="mt-1 block text-xs text-muted">Menor valor gera respostas mais consistentes.</span></Field></div><ToggleRow label="Permitir fallback local" description="Mantenha o atendimento disponível quando o provedor de modelo estiver indisponível." checked={settings.allowLocalFallback} onChange={() => toggle("allowLocalFallback")} /></SettingsSection>

      <SettingsSection icon={Bell} title="Notificações operacionais" description="Escolha quais acontecimentos devem chamar a atenção da equipe."><ToggleRow label="Novos handoffs" description="Avise quando uma conversa precisar de atendimento humano." checked={settings.notifyHandoffs} onChange={() => toggle("notifyHandoffs")} /><ToggleRow label="Falhas de execução" description="Avise sobre jobs com erro, retries ou filas paradas." checked={settings.notifyFailures} onChange={() => toggle("notifyFailures")} /><ToggleRow label="Publicações e mudanças" description="Avise quando uma versão de agente for publicada ou revertida." checked={settings.notifyDeployments} onChange={() => toggle("notifyDeployments")} /></SettingsSection>

      <SettingsSection icon={ShieldCheck} title="Segurança e governança" description="Políticas locais de proteção para ações executadas pelos agentes."><ToggleRow label="Confirmar ferramentas de alto risco" description="Exija aprovação humana antes de ações potencialmente irreversíveis." checked={settings.confirmHighRiskTools} onChange={() => toggle("confirmHighRiskTools")} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Ambiente padrão"><select value={settings.defaultEnvironment} onChange={(e) => updateSettings({ defaultEnvironment: e.target.value as PlatformSettings["defaultEnvironment"] })} className="h-10 w-full rounded-md border border-border bg-bg px-3 text-sm"><option value="development">Development</option><option value="staging">Staging</option><option value="production">Production</option></select></Field><Field label="Workspace ativo"><Input value={workspace?.name ?? "Nenhum workspace selecionado"} readOnly /></Field></div></SettingsSection>
    </div><aside className="space-y-3"><QuickLink icon={PlugIcon} title="Conectores e canais" description="Credenciais, webhooks e adapters" href="/connections" /><QuickLink icon={Database} title="Conhecimento" description="Base usada pelos agentes" href="/agents" /><QuickLink icon={Workflow} title="Workflows" description="Gatilhos, filas e aprovações" href="/workflows" /><QuickLink icon={KeyRound} title="Execuções" description="Logs e rastreabilidade" href="/runs" /><Card className="mt-5 bg-elevated p-4"><SlidersHorizontal className="size-5 text-accent" /><h3 className="mt-3 font-display font-semibold">Configuração por ambiente</h3><p className="mt-2 text-xs leading-relaxed text-muted">Preferências do console são locais. Segredos, permissões e credenciais devem ser configurados por workspace e ambiente.</p></Card></aside></div></div></AppShell>;
}

function PlugIcon({ className }: { className?: string }) { return <Boxes className={className} />; }
function SettingsSection({ icon: Icon, title, description, children }: { icon: ComponentType<{ className?: string }>; title: string; description: string; children: ReactNode }) { return <Card className="p-5"><div className="flex gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-accent/10 text-accent"><Icon className="size-4" /></div><div className="min-w-0 flex-1"><h2 className="font-display text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted">{description}</p></div></div><div className="mt-5 divide-y divide-border">{children}</div></Card>; }
function ToggleRow({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) { return <div className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs leading-relaxed text-muted">{description}</p></div><Switch checked={checked} onCheckedChange={onChange} aria-label={label} /></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm"><span className="mb-1.5 block text-xs font-medium text-muted">{label}</span>{children}</label>; }
function QuickLink({ icon: Icon, title, description, href }: { icon: ComponentType<{ className?: string }>; title: string; description: string; href: "/connections" | "/agents" | "/workflows" | "/runs" }) { return <Link to={href} className="flex items-center gap-3 rounded-xl border border-border bg-surface p-3 transition-colors hover:bg-elevated"><span className="flex size-8 items-center justify-center rounded-lg bg-elevated text-muted"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{title}</span><span className="block truncate text-xs text-muted">{description}</span></span><ChevronRight className="size-4 text-subtle" /></Link>; }
