import type { ConnectorContext, HealthcheckResult, ConnectorInstance } from "./runtime.ts";

type MetaConfig = { baseUrl?: string; graphVersion?: string; phoneNumberId?: string; timeoutMs?: number };
export type MetaTextMessage = { baseUrl?: string; graphVersion?: string; phoneNumberId: string; recipient: string; text: string; timeoutMs?: number };
export type MetaDispatchResult = { status: "sent" | "failed" | "unknown"; code: "ok" | "invalid_request" | "secret_unavailable" | "unauthorized" | "rate_limited" | "provider_error" | "timeout" | "network_error"; httpStatus?: number; latencyMs: number; message: string; providerMessageId?: string };

function config(value: unknown): MetaConfig { const v = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; return { baseUrl: typeof v.baseUrl === "string" ? v.baseUrl : "https://graph.facebook.com", graphVersion: typeof v.graphVersion === "string" ? v.graphVersion : undefined, phoneNumberId: typeof v.phoneNumberId === "string" ? v.phoneNumberId : undefined, timeoutMs: typeof v.timeoutMs === "number" ? v.timeoutMs : undefined }; }
function url(value: string): URL { const parsed = new URL(value); const local = ["localhost", "127.0.0.1", "::1"].includes(parsed.hostname); if (parsed.protocol !== "https:" && !local) throw new Error("META_CONFIG_INVALID"); return parsed; }
function timeout(value: number | undefined): number { return value === undefined ? 10000 : Math.min(Math.max(Math.round(value), 500), 30000); }
function recipient(value: string): string { const normalized = value.trim().replace(/\D/g, ""); if (!/^\d{8,20}$/.test(normalized)) throw new Error("RECIPIENT_INVALID"); return normalized; }
function endpoint(baseUrl: string, version: string, phoneNumberId: string, path: string): string { const base = url(baseUrl); return new URL(`/${encodeURIComponent(version)}/${encodeURIComponent(phoneNumberId)}${path}`, base).toString(); }
function resultFor(status: number, latencyMs: number): MetaDispatchResult { if (status === 400) return { status: "failed", code: "invalid_request", httpStatus: status, latencyMs, message: "Meta rejected the message payload" }; if (status === 401 || status === 403) return { status: "failed", code: "unauthorized", httpStatus: status, latencyMs, message: "Meta rejected the configured access token" }; if (status === 429) return { status: "unknown", code: "rate_limited", httpStatus: status, latencyMs, message: "Meta rate limit reached" }; if (status >= 500) return { status: "unknown", code: "provider_error", httpStatus: status, latencyMs, message: "Meta returned a provider error" }; return { status: "failed", code: "network_error", httpStatus: status, latencyMs, message: "Meta returned a non-success status" }; }

export class MetaCloudApiAdapter {
  readonly provider = "meta";
  validateConfig(value: unknown): void { const c = config(value); if (!c.phoneNumberId || !c.graphVersion) throw new Error("META_CONFIG_INVALID"); url(c.baseUrl!); }
  async healthcheck(instance: ConnectorInstance, ctx: ConnectorContext): Promise<HealthcheckResult> { const started = Date.now(); try { this.validateConfig(instance.config); const c = config(instance.config); const token = await ctx.getSecret("api_key"); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout(c.timeoutMs)); try { const response = await fetch(endpoint(c.baseUrl!, c.graphVersion!, c.phoneNumberId!, "?fields=id,display_phone_number,verified_name"), { headers: { accept: "application/json", authorization: `Bearer ${token}` }, signal: controller.signal, redirect: "error" }); const latencyMs = Date.now() - started; if (response.ok) return { status: "healthy", code: "ok", httpStatus: response.status, latencyMs, message: "Meta Cloud API accepted the phone number query" }; const mapped = resultFor(response.status, latencyMs); return { status: mapped.status === "sent" ? "healthy" : mapped.status === "unknown" ? "degraded" : "unhealthy", code: mapped.code === "invalid_request" ? "configuration_invalid" : mapped.code, httpStatus: mapped.httpStatus, latencyMs, message: mapped.message }; } finally { clearTimeout(timer); } } catch (error) { const code = error instanceof Error && error.name === "AbortError" ? "timeout" : error instanceof Error && error.message === "META_CONFIG_INVALID" ? "configuration_invalid" : error instanceof Error && error.message === "SECRET_NOT_FOUND" ? "secret_unavailable" : "network_error"; return { status: code === "network_error" ? "unhealthy" : code === "timeout" ? "unhealthy" : code === "secret_unavailable" ? "unhealthy" : "unhealthy", code, latencyMs: Date.now() - started, message: code === "configuration_invalid" ? "Meta connector configuration is invalid" : code === "secret_unavailable" ? "The Meta access token could not be resolved server-side" : code === "timeout" ? "Meta healthcheck timed out" : "Meta healthcheck failed" }; } }
}

export class MetaTextDispatcher {
  async sendText(message: MetaTextMessage, ctx: ConnectorContext): Promise<MetaDispatchResult> { const started = Date.now(); let c: MetaConfig; let to: string; try { c = config(message); c.phoneNumberId = message.phoneNumberId; c.graphVersion = message.graphVersion ?? c.graphVersion; this.validate(c); to = recipient(message.recipient); if (!message.text.trim() || message.text.length > 4096) throw new Error("TEXT_INVALID"); } catch { return { status: "failed", code: "invalid_request", latencyMs: Date.now() - started, message: "Meta message configuration is invalid" }; } let token: string; try { token = await ctx.getSecret("api_key"); } catch { return { status: "failed", code: "secret_unavailable", latencyMs: Date.now() - started, message: "The Meta access token could not be resolved server-side" }; } const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout(c.timeoutMs)); try { const response = await fetch(endpoint(c.baseUrl!, c.graphVersion!, c.phoneNumberId!, "/messages"), { method: "POST", headers: { accept: "application/json", "content-type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify({ messaging_product: "whatsapp", recipient_type: "individual", to, type: "text", text: { preview_url: false, body: message.text } }), signal: controller.signal, redirect: "error" }); const latencyMs = Date.now() - started; if (response.ok) { let id: string | undefined; try { const body = await response.json() as { messages?: Array<{ id?: unknown }> }; id = typeof body.messages?.[0]?.id === "string" ? body.messages[0].id.slice(0, 240) : undefined; } catch (error) { void error; } return { status: "sent", code: "ok", httpStatus: response.status, latencyMs, message: "Meta Cloud API accepted the text message", ...(id ? { providerMessageId: id } : {}) }; } return resultFor(response.status, latencyMs); } catch (error) { const aborted = error instanceof Error && error.name === "AbortError"; return { status: "unknown", code: aborted ? "timeout" : "network_error", latencyMs: Date.now() - started, message: aborted ? "Meta message dispatch timed out" : "Meta message dispatch failed" }; } finally { clearTimeout(timer); } }
  private validate(value: MetaConfig): void { if (!value.phoneNumberId || !value.graphVersion) throw new Error("META_CONFIG_INVALID"); url(value.baseUrl ?? "https://graph.facebook.com"); }
}
