import assert from "node:assert/strict";
import { createServer } from "node:http";
import test from "node:test";
import { MetaCloudApiAdapter, MetaTextDispatcher } from "./meta-messaging.ts";

function server() { const requests: Array<{ method: string; url: string; headers: Record<string, string>; body: string }> = []; const http = createServer((req, res) => { let body = ""; req.on("data", (chunk) => { body += chunk; }); req.on("end", () => { requests.push({ method: req.method ?? "", url: req.url ?? "", headers: req.headers as Record<string, string>, body }); res.setHeader("content-type", "application/json"); res.end(req.url?.endsWith("/messages") ? JSON.stringify({ messages: [{ id: "wamid.test" }] }) : JSON.stringify({ id: "phone-1", display_phone_number: "+5511999999999" })); }); }); return { http, requests }; }

test("Meta adapter performs healthcheck and sends documented text payload", async () => { const { http, requests } = server(); await new Promise<void>((resolve) => http.listen(0, "127.0.0.1", resolve)); try { const address = http.address(); assert.ok(address && typeof address === "object"); const baseUrl = `http://127.0.0.1:${address.port}`; const ctx = { workspaceId: "ws", connectionId: "c", traceId: "t", getSecret: async (name: string) => { assert.equal(name, "api_key"); return "fixture-token"; } }; const health = await new MetaCloudApiAdapter().healthcheck({ id: "c", provider: "meta", secretRef: "ref", config: { baseUrl, graphVersion: "v-test", phoneNumberId: "phone-1" } }, ctx); assert.equal(health.status, "healthy"); const sent = await new MetaTextDispatcher().sendText({ baseUrl, graphVersion: "v-test", phoneNumberId: "phone-1", recipient: "+55 (11) 99999-9999", text: "Olá" }, ctx); assert.equal(sent.status, "sent"); assert.equal(sent.providerMessageId, "wamid.test"); assert.equal(requests[0]?.headers.authorization, "Bearer fixture-token"); assert.deepEqual(JSON.parse(requests[1]?.body ?? "{}"), { messaging_product: "whatsapp", recipient_type: "individual", to: "5511999999999", type: "text", text: { preview_url: false, body: "Olá" } }); } finally { await new Promise<void>((resolve, reject) => http.close((error) => error ? reject(error) : resolve())); } });

test("Meta adapter rejects insecure remote endpoints", async () => { assert.throws(() => new MetaCloudApiAdapter().validateConfig({ baseUrl: "http://provider.example", graphVersion: "v-test", phoneNumberId: "phone" }), /META_CONFIG_INVALID/); });
