import { useState } from "react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogTrigger } from "./ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { provisionMetaConnectionCredential } from "@/lib/multitenancy/api";
import { useNexo } from "@/lib/store";
import { useWorkspaceData } from "@/lib/multitenancy/use-workspace-data";
import type { Connection } from "@/lib/types";

export function MetaCredentialDialog({ connection }: { connection: Connection }) {
  const workspaceId = useNexo((s) => s.workspaceId); const backendReady = useNexo((s) => s.backendReady); const { refresh } = useWorkspaceData(); const [open, setOpen] = useState(false); const [accessToken, setAccessToken] = useState(""); const [appSecret, setAppSecret] = useState(""); const [verifyToken, setVerifyToken] = useState(""); const [phoneNumberId, setPhoneNumberId] = useState(connection.phoneNumberId ?? ""); const [graphVersion, setGraphVersion] = useState("v23.0"); const [baseUrl, setBaseUrl] = useState("https://graph.facebook.com"); const [busy, setBusy] = useState(false);
  async function submit() { if (!workspaceId || !accessToken.trim() || !appSecret.trim() || !verifyToken.trim() || !phoneNumberId.trim() || !graphVersion.trim()) { toast("Preencha todos os campos da Meta."); return; } setBusy(true); try { await provisionMetaConnectionCredential({ data: { workspaceId, connectionId: connection.id, accessToken, appSecret, verifyToken, phoneNumberId, graphVersion, baseUrl } }); await refresh(workspaceId); setAccessToken(""); setAppSecret(""); setVerifyToken(""); setOpen(false); toast("Credenciais Meta provisionadas no cofre."); } catch { toast("Não foi possível provisionar as credenciais Meta. Verifique o backend de secrets e sua permissão administrativa."); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" className="w-full" disabled={!backendReady}>Configurar Meta Cloud API</Button></DialogTrigger><DialogContent title="Onboarding Meta WhatsApp Cloud API"><p className="mt-1 mb-4 text-sm text-muted">Os três segredos são enviados somente ao backend e armazenados no cofre. O Verify Token deve ser o mesmo informado no painel de Webhooks da Meta.</p><div className="flex flex-col gap-3"><div className="flex flex-col gap-1.5"><Label htmlFor="meta-token">Access Token</Label><Input id="meta-token" type="password" value={accessToken} onChange={(e) => setAccessToken(e.target.value)} autoComplete="new-password" /></div><div className="flex flex-col gap-1.5"><Label htmlFor="meta-app-secret">App Secret</Label><Input id="meta-app-secret" type="password" value={appSecret} onChange={(e) => setAppSecret(e.target.value)} autoComplete="new-password" /></div><div className="flex flex-col gap-1.5"><Label htmlFor="meta-verify">Verify Token</Label><Input id="meta-verify" type="password" value={verifyToken} onChange={(e) => setVerifyToken(e.target.value)} autoComplete="new-password" /></div><div className="flex flex-col gap-1.5"><Label htmlFor="meta-phone">Phone Number ID</Label><Input id="meta-phone" value={phoneNumberId} onChange={(e) => setPhoneNumberId(e.target.value)} /></div><div className="flex flex-col gap-1.5"><Label htmlFor="meta-version">Graph API version</Label><Input id="meta-version" value={graphVersion} onChange={(e) => setGraphVersion(e.target.value)} placeholder="v23.0" /></div><div className="flex flex-col gap-1.5"><Label htmlFor="meta-base">Graph API base URL</Label><Input id="meta-base" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} /></div></div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => void submit()} disabled={busy}>{busy ? "Provisionando…" : "Salvar no cofre"}</Button></div></DialogContent></Dialog>;
}
