/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsIdRouteImport } from './routes/agents/$id'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as NexoBotAuditRouteImport } from './routes/nexo-bot/audit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MarketplaceAgentsProductIdRouteImport } from './routes/marketplace/agents/$productId'
import { Route as MarketplaceInstalledIndexRouteImport } from './routes/marketplace/installed/index'
import { Route as MarketplaceInstalledInstallationIdRouteImport } from './routes/marketplace/installed/$installationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const NexoBotAuditRoute = NexoBotAuditRouteImport.update({
  id: '/nexo-bot/audit',
  path: '/nexo-bot/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceAgentsProductIdRoute =
  MarketplaceAgentsProductIdRouteImport.update({
    id: '/marketplace/agents/$productId',
    path: '/marketplace/agents/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceInstalledIndexRoute =
  MarketplaceInstalledIndexRouteImport.update({
    id: '/marketplace/installed/',
    path: '/marketplace/installed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceInstalledInstallationIdRoute =
  MarketplaceInstalledInstallationIdRouteImport.update({
    id: '/marketplace/installed/$installationId',
    path: '/marketplace/installed/$installationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/nexo-bot/audit': typeof NexoBotAuditRoute
  '/agents/': typeof AgentsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/marketplace/agents/$productId': typeof MarketplaceAgentsProductIdRoute
  '/marketplace/installed/$installationId': typeof MarketplaceInstalledInstallationIdRoute
  '/marketplace/installed/': typeof MarketplaceInstalledIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/nexo-bot/audit': typeof NexoBotAuditRoute
  '/agents': typeof AgentsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/marketplace/agents/$productId': typeof MarketplaceAgentsProductIdRoute
  '/marketplace/installed/$installationId': typeof MarketplaceInstalledInstallationIdRoute
  '/marketplace/installed': typeof MarketplaceInstalledIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connections': typeof ConnectionsRoute
  '/create': typeof CreateRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/nexo-bot/audit': typeof NexoBotAuditRoute
  '/agents/': typeof AgentsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/marketplace/agents/$productId': typeof MarketplaceAgentsProductIdRoute
  '/marketplace/installed/$installationId': typeof MarketplaceInstalledInstallationIdRoute
  '/marketplace/installed/': typeof MarketplaceInstalledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/connections'
    | '/create'
    | '/guide'
    | '/inbox'
    | '/login'
    | '/metrics'
    | '/runs'
    | '/settings'
    | '/workflows'
    | '/agents/$id'
    | '/nexo-bot/audit'
    | '/agents/'
    | '/marketplace/'
    | '/api/auth/$'
    | '/marketplace/agents/$productId'
    | '/marketplace/installed/$installationId'
    | '/marketplace/installed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/connections'
    | '/create'
    | '/guide'
    | '/inbox'
    | '/login'
    | '/metrics'
    | '/runs'
    | '/settings'
    | '/workflows'
    | '/agents/$id'
    | '/nexo-bot/audit'
    | '/agents'
    | '/marketplace'
    | '/api/auth/$'
    | '/marketplace/agents/$productId'
    | '/marketplace/installed/$installationId'
    | '/marketplace/installed'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/connections'
    | '/create'
    | '/guide'
    | '/inbox'
    | '/login'
    | '/metrics'
    | '/runs'
    | '/settings'
    | '/workflows'
    | '/agents/$id'
    | '/nexo-bot/audit'
    | '/agents/'
    | '/marketplace/'
    | '/api/auth/$'
    | '/marketplace/agents/$productId'
    | '/marketplace/installed/$installationId'
    | '/marketplace/installed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CreateRoute: typeof CreateRoute
  GuideRoute: typeof GuideRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  NexoBotAuditRoute: typeof NexoBotAuditRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MarketplaceAgentsProductIdRoute: typeof MarketplaceAgentsProductIdRoute
  MarketplaceInstalledInstallationIdRoute: typeof MarketplaceInstalledInstallationIdRoute
  MarketplaceInstalledIndexRoute: typeof MarketplaceInstalledIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexo-bot/audit': {
      id: '/nexo-bot/audit'
      path: '/nexo-bot/audit'
      fullPath: '/nexo-bot/audit'
      preLoaderRoute: typeof NexoBotAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/agents/$productId': {
      id: '/marketplace/agents/$productId'
      path: '/marketplace/agents/$productId'
      fullPath: '/marketplace/agents/$productId'
      preLoaderRoute: typeof MarketplaceAgentsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/installed/': {
      id: '/marketplace/installed/'
      path: '/marketplace/installed'
      fullPath: '/marketplace/installed/'
      preLoaderRoute: typeof MarketplaceInstalledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/installed/$installationId': {
      id: '/marketplace/installed/$installationId'
      path: '/marketplace/installed/$installationId'
      fullPath: '/marketplace/installed/$installationId'
      preLoaderRoute: typeof MarketplaceInstalledInstallationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ConnectionsRoute: ConnectionsRoute,
  CreateRoute: CreateRoute,
  GuideRoute: GuideRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  WorkflowsRoute: WorkflowsRoute,
  AgentsIdRoute: AgentsIdRoute,
  NexoBotAuditRoute: NexoBotAuditRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MarketplaceAgentsProductIdRoute: MarketplaceAgentsProductIdRoute,
  MarketplaceInstalledInstallationIdRoute:
    MarketplaceInstalledInstallationIdRoute,
  MarketplaceInstalledIndexRoute: MarketplaceInstalledIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
